= ```Smart_Immo``` Documentation
FFN-Team
2023-11-26
:toc:
//:revnumber: {project-version}
//:example-caption!:
ifndef::sourcedir[:sourcedir: ../../main/java/com/gangdestrois/smartimmo]
ifndef::modelsdir[:modelsdir: models]

== Synthèse

=== Identité du projet

* *Nom du projet* : TechnImmo

=== Membres de l'équipe

* Niraiksan Ravimohan
* Florine Philippe
* Fanuel Mehari

=== Présentation du projet

En théorie, la prospection représente 80% du temps de travail d'un agent immobilier. Cependant, de nombreux agents passent trop de temps sur les activités de vente ou à utiliser des logiciels, au détriment de leur présence sur le terrain. Comment pouvons-nous les aider à recentrer leurs efforts sur leur cœur de métier ? Il est essentiel de leur fournir un support capable de collecter et d’organiser les informations afin d’optimiser leur temps de présence sur le terrain.

C'est dans cette optique que nous avons entrepris un projet professionnel visant à créer une application conviviale et complète spécialement conçue pour aider les agents immobiliers. Nous tirons inspiration de ce cours pour concrétiser notre initiative, c'est là notre principale source de motivation.

Nous avons analysé attentivement les concurrents pour ne pas négliger les fonctionnalités déjà existantes, tout en cherchant à innover et à combler les besoins non satisfaits des agents immobiliers. Notre objectif est de développer une application qui combine le meilleur des deux mondes : les fonctionnalités éprouvées et des solutions innovantes pour améliorer l'efficacité et l'expérience des agents immobiliers.

=== Les personas et leurs fonctionnalités

1. *Agent immobilier*

* *Prospection* : Intégration de cartes pour localiser les biens sur une carte interactive.
* *Dashboard* : Fournit un tableau de bord avec des graphiques, des courbes et des tableaux pour suivre et gérer l'inventaire des biens, l'activité, et offre des statistiques de marché.
* *Gestion des biens immobiliers* : Permet d'ajouter, modifier, supprimer des annonces de biens, télécharger des photos, vidéos, et offre une alerte pour les nouveaux biens.
* *Gestion des clients (prospects)* : Permet la gestion de clients potentiels, suit leurs préférences, et offre des rappels et notifications.
* *Gestion des offres et des négociations* : Inclut le suivi des offres, des négociations et la documentation des transactions.
* *Gestion de projets potentiels* : Enregistre les projets futurs des clients avec des rappels.
* *Agenda et planification* : Offre un calendrier intégré avec des tâches, des rappels et des alertes.
* *Documents* : Permet le suivi des documents et contrats, la création de supports marketing personnalisés, et la signature électronique.
* *Communication* : Inclut des fonctionnalités de partage sur les réseaux sociaux, de messagerie instantanée, et d'envoi de notifications aux clients.
* *Formation et support* : Offre des ressources de formation et un support client.
* *Outils de recherche avancée* : Propose une recherche par emplacement, prix, type de bien, et d'autres critères pertinents.

=== Prévisions marketing

Stratégies :

* Démarcher les agents immobiliers sur place, sur les réseaux sociaux
* Faire jouer le réseau professionnel / personnel
* Faire un site web

== Aspects techniques

=== README

==== To do before setting up your development environment

* Install https://jdk.java.net/java-se-ri/21[Java 21]
* Install https://docs.docker.com/engine/install/[Docker]
* Install https://docs.docker.com/engine/install/[Docker Compose]
* Install your favorite IDE (IntelliJ, Eclipse, Visual Source Code, ...)

==== How to setup your local development environment

.Setting up Docker

Run docker-compose.yml

.Setting up TechnImmo

[source,shell]
----
mvn clean install
mvn flyway:migrate
----

.Run the application in local
* Use your IDE to create a run configuration from SmartimmoApplication.java
* Use profile log-txt to prevent from logging in json

==== Testing

Unit tests

[source,shell]
----
mvn test
----

All tests

[source,shell]
----
mvn clean verify
----

=== Type d'application

C'est une application *web*.

=== Schéma architectural

* *Architecture du back* : architecture hexagonale
* *API REST*

=== Plateforme technologique

* *Langage back-end* : Java
* *Langage front-end* : ReactJS
* *Framework de test* : JUnit
* *Framework de lien métier/API* : Spring
* *Framework de métier/persistance* : JPA Hibernate

=== Plateforme opérationnelle

* *Gestion des versions* : GitHub
* *Build* : Maven
* *Qualité de code* : Code Climate
* *CI* : GitHub Actions

=== Interconnexion avec systèmes / API distantes

* *Google Map*
* *Google Agenda*

=== Acquisition de données, usage intelligent des données

Utilisation pour l’automatisation, l’aide à la décision et l'excellence de l’expérience client.

Par exemple : amélioration de la recherche des biens, personnalisation des recommandations, évaluation immobilière…

== Modélisation

=== v0.0.2

==== Feature 1 : Notifier l'agent quand la date d'un projet anticipé approche

==== Feature 2 : Créer un portfolio des biens pouvant plaire à un acquéreur

=== v0.0.3

=== Feature 1 : Créer le dashboard de l'agent immobilier