version: "3.8"
name: "technimmo"

services:

  # PostgreSQL
  db-pg-technimmo:
    image: postgres:14.7-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command: ["postgres", "-c", "wal_level=logical"]
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql