# Remarque : pour que le docker fonctionne correctement,
# il ne doit pas y avoir plusieurs serveurs qui tournent sur le port voulu.
version: "3.8"
services:
  technimmo:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql