package com.gangdestrois.smartimmo.infrastructure.rest.error;

public enum ExceptionEnum {
    ALREADY_ASSIGNED_ADDRESS,
    EMAIL_CONTENT_ERROR,
    NOT_VALID_ARGUMENT,
    GOOGLE_UNAUTHORIZED,
    CONTACT_ON_SOCIAL_MEDIA_UNAUTHORIZED,
    BUYER_NOT_FOUND,
    EMAIL_SENDER_NOT_FOUND,
    PROJECT_NOT_FOUND,
    PROSPECT_NOT_FOUND,
    SECRETS_NOT_FOUND,
    NOTIFICATION_NOT_FOUND,
    ADDRESS_NOT_FOUND,
    PROPERTY_NOT_FOUND

}
