package com.gangdestrois.smartimmo.domain.error;

public enum ExceptionEnum {
    ALREADY_ASSIGNED_ADDRESS,
    EMAIL_CONTENT_ERROR,
    GOOGLE_CREDENTIALS_ERROR,
    CONVERT_DOCUMENT_ERROR,
    DOCUMENT_ERROR,
    NOT_VALID_ARGUMENT,
    EVENT_NOT_SUBSCRIBE,
    GOOGLE_UNAUTHORIZED,
    CONTACT_ON_SOCIAL_MEDIA_UNAUTHORIZED,
    BUYER_NOT_FOUND,
    EMAIL_SENDER_NOT_FOUND,
    PROJECT_NOT_FOUND,
    PROSPECT_NOT_FOUND,
    SECRETS_NOT_FOUND,
    NOTIFICATION_NOT_FOUND,
    ADDRESS_NOT_FOUND,
    PROPERTY_NOT_FOUND,
    DOCUMENT_NAME_NOT_SPECIFIED,
    DOCUMENT_WITH_SAME_NAME_ALREADY_EXISTS

}
