@startuml
'https://plantuml.com/sequence-diagram

autonumber

PotentialProjectManager -> PotentialProjectSpi: findPotentialProjectToNotify
PotentialProjectManager <-- PotentialProjectSpi: PotentialProjectToNotify : List<PotentialProject>
PotentialProjectManager -> PotentialProjectNotificationStrategy : makeNotification
PotentialProjectNotificationStrategy -> EventManager
EventManager -> NotificationAlertListener : update
PotentialProjectManager -> PotentialProjectNotificationStrategy : getNotification
PotentialProjectManager <-- PotentialProjectNotificationStrategy : List<Event<PotentialProject>>
@enduml