name: Java CI with Maven
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout le code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Generate Code Coverage Report
      run: mvn jacoco:report
