name: Java CI with Maven
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
